### ISSUE TITLE
Scroller-example doesn't work on Win+Firefox

### ISSUE THREAD

**Issue by judofyr** [somebee/imba#12]
From: https://news.ycombinator.com/item?id=10093762

> edit: @judofyr, the Scroller example app doesn't work for me on Firefox 40.0.2 on Win 8. It works in Chrome.

**Comment by somebee** [comment]
It seems to be due to this: http://stackoverflow.com/questions/16788995/mousewheel-event-is-not-triggering-in-firefox-browser. Either we should not support the mousewheel-event at all, or we need to make mousewheel listener register differently in dom.events.

**Comment by somebee** [comment]
This should now be fixed and pushed to the site.
