### ISSUE TITLE
Include `isNaN` in predeclared globals

### ISSUE THREAD

**Issue by foxbunny** [somebee/imba#129]
Not sure if there's a rationale behind `isNaN` not being a global, but if it's just an oversight, I would very much vote for inclusion.

**Comment by somebee** [comment]
Originally I thought it was better to use Number.isNaN (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN), but I'm definitely open for including it.

**Comment by foxbunny** [comment]
I believe it's got different behavior in that it will only return `true` for actual `NaN`, while `window.isNaN` will also return true for anything that is not strictly a number. Not sure which is 'better', but `isNaN` is what I normally go for. Also, it's the one on the global object, so it would make sense to include it simply to save a few `extern isNaN` calls. :)

**Comment by somebee** [comment]
Good point. Will include in 1.4.1 :)
