### ISSUE TITLE
Ruby gem for imba?

### ISSUE THREAD

**Issue by victorbojica** [somebee/imba#13]
Is there any way this can be ported to gem for ruby (since they are very alike) ? Thx.

**Comment by judofyr** [comment]
Do you want to have support for it in the asset pipeline? I've been thinking about creating a gem for that.

**Comment by victorbojica** [comment]
Either way. As long as i don't have to use node. I've tried taking a look and maybe do it myself, but i never created a gem and i'm a bit confused on this topic. I can help tough.

**Comment by krazyjakee** [comment]
@judofyr Ooh ooh me me yes please. Asset pipeline please. Thank you :dancers:

**Comment by judofyr** [comment]
I've started working on it.

Source gem: https://github.com/judofyr/imba-source
Compiler gem: https://github.com/judofyr/imba-template

Next up is a Rails plugin.

**Comment by krazyjakee** [comment]
@judofyr big hype, thank you :cake:

**Comment by judofyr** [comment]
And the Rails gem is here: https://github.com/judofyr/imba-rails.

Now I'm only blocking on #23.

**Comment by judofyr** [comment]
Pushed: https://rubygems.org/gems/imba-rails.

See https://github.com/judofyr/imba-rails for usage and bug reports.

**Comment by somebee** [comment]
```
def app
    #app
```
In this example (from imba-rails) app would be a local function, unless you compile with --bare option. Is this intentional? It seems as calling app() from outside in the view would result in an error (undefined function)? Or maybe I don't fully understand the example.

**Comment by judofyr** [comment]
Oops. Very good point. I was testing the `bare`-functionality and didn't update the README/code. Updated it now to say `def window.app`.
