### ISSUE TITLE
Module support?

### ISSUE THREAD

**Issue by jussiarpalahti** [somebee/imba#15]
I found some files in the repo that seem to indicate Imba having support for modules.

Is this already working and how it can be used? Or if not, is there any plans to support this?

And what about importing and using JS modules?

This is, IMHO, the best missing feature in coffeescript, and something I've come to rely on with ES6.

Other than that, Imba language looks very promising. I have to take it for a spin next time I have a short task to do.

**Comment by pateketrueke** [comment]
> And what about importing and using JS modules?

I think you may use this:

```
import stuff from 'moduleName'
```

Which compiles to:

```
var stuff=require('moduleName').stuff;
```

You can bundle all your scripts using Webpack or Browserify and have fun.
