### ISSUE TITLE
Export latest imba.js file

### ISSUE THREAD

**Issue by cavneb** [somebee/imba#16]
Is there a way to export the latest imba.js library file? I see that all your examples require imba.js

**Comment by somebee** [comment]
Good question. I've always been developing locally, and it is included in the repo at [lib/browser](https://github.com/somebee/imba/tree/master/lib/browser).

## CLI
I just [commited](https://github.com/somebee/imba/commit/969575e16ca9d3a97a54a482e051e2c5829dea60) a simple addition to the CLI (as per your request). Now you can execute `imba export-runtime <path>` to export imba.js into the specified path. If are at the root of your project, simply execute `imba export-runtime .`.
If you add -m you get the minified version.

## Browserify
If you use browserify you can simply do `require 'imba'`in your app (usually at the top of the 'main' file). You will need to have imba installed locally in your project though (not only `npm install -g imba`, but also `npm install imba --save`).

## Downlaod
It is included in the repo at [lib/browser](https://github.com/somebee/imba/tree/master/lib/browser). You can download it from there, but I see that it is not a very good workflow.
