### ISSUE TITLE
Replacing content of element

### ISSUE THREAD

**Issue by michaelowens** [somebee/imba#17]
All the examples seem to append by doing e.g. `$$(#app).append <todolist>`.

I can't seem to find any reference in the ElementTag to a function that would replace the content. Am I missing it or could this be something that that could be added?

Could be nice for e.g. placeholders.

```
<div id="app">Loading...</div>
``` 

and then e.g. like in jQuery:

```
$$(#app).html <todolist>
```

**Comment by somebee** [comment]
Sorry for the *extreme* lack of documentation at the moment. Usually you would not even use append, as static rendering (like in http://imba.io/#/examples/dynamic.imba) is much easier and more intuitive. You should be able to do `$$(#app).children = ["Loading...",<li>]` or if it is just text, you can do `$$(#app).text = "Loading..."`

If your div has id #app you don't need `$$(#app)` to select it by the way, all elements with id can be accessed directly through `#myid`. So it would be:

```imba
#app.text = "Loading..."
# wait for something

#app.empty.append <todolist>

# or #app.children = [<todolist>]
```

**Comment by michaelowens** [comment]
Oh, I see. Thanks for clearing that up. It's sometimes a bit of a hassle, but maybe also fun to be more pushed towards the source and figuring out *how* it works. None the less, loving the language so far!
