### ISSUE TITLE
Remove is not working

### ISSUE THREAD

**Issue by krazyjakee** [somebee/imba#21]
I am working from the master branch.

`<div.btn.btn-danger.input-group-addon :tap='remove_input'> "X"`

```ruby
def remove_input e
    console.log e.target.parent.parent.remove
```
Doesn't work but...

```ruby
def remove_input e
    console.log e.target.parent.parent.empty
```

does work. Of course it only removes children and not the parent element as well.

**Comment by somebee** [comment]
I guess this is the result of our non-existent documentation (and possibly weird naming). `tag.remove` expects a node as an argument - it is for removing children. The method you are looking for is `tag.orphanize`. We should probably rename the methods to:

`tag.remove` -> `tag.removeChild`
`tag.orphanize` -> `tag.remove`

As for the documentation, I'm working on it. It's coming very soon :)

**Comment by krazyjakee** [comment]
No pressure mate, I am really enjoying it so far and starting to find it more useful the more I get working.
