### ISSUE TITLE
browser/compiler.js is broken

### ISSUE THREAD

**Issue by judofyr** [somebee/imba#23]
`browser/compiler.js` is currently broken (it seems to miss the `./index`-module).

Could I also suggest to name it `imba.compiler.js`? That means it would be possible to add the `browser`-directory directly to the load path for assets pipelines.

**Comment by somebee** [comment]
Will push fix later today. Should probably bump version at the same time.

**Comment by somebee** [comment]
Pushed v0.12.1 now, where I have renamed the compiler to `imbac.js`instead. We should consider splitting the compiler and runtime in different repos, and I'm also thinking about moving the compile/analyze/watch parts of the CLI to a `bin/imbac` as well.
