### ISSUE TITLE
Imba events issues

### ISSUE THREAD

**Issue by TenSoon** [somebee/imba#24]
Hello,

I've been playing with Imba for couple of days now and I am loving it so far.
Today I have been experimenting with events and it seems I'm stuck - I can't cancel the "tap" default event:

```
tag testing

	def taptest e
		e.cancel
		console.log e

	def render
		<self>
			<a href="#" :tap="taptest"> "Testing"

$$(body).prepend <testing>
```

I am also interested in using the `Imba.Event.keycombo` with the above code but the method spits out nothing. Am I missing something?

Any help is much appreciated. 
Thanks!

**Comment by judofyr** [comment]
Hm. Currently the `tap`-event is not properly wrapping the `click`-event. This also needs to be consistent with the touch behavior though. We should probably have a file under `test/` which demonstrates the various event handlers (e.g. `:tap` in a scrollable list) that can be easily tested on multiple devices.

**Comment by TenSoon** [comment]
After I've registered the "click" event and used `:click=...` instead of `:tap=...`, it worked fine.
I'm still figuring out what works best and the test folder is a big help :)
Anyways, thanks for the reply. Back to coding... ;)
