### ISSUE TITLE
Cannot get correct height and width of elements during initial render

### ISSUE THREAD

**Issue by denyeo** [somebee/imba#29]
I'm trying to resize (set the height and width of) an element based on the rendered height and width of another element. Specifically, I want to make a `<div>` (called `markercontainer`) the same size as a sibling `<img>` (called `canvasimg`).

After some experimentation, I attempted to read the size of `canvasimg` directly (using `.dom()`) in the render function:
```
    def render
        <self>
            (var canvasimg = <img.canvasimg src="img/interior-01.jpg">)
            (var markercontainer = <div.marker-container>
            ).css({height: canvasimg.dom():height, width: canvasimg.dom():width})
```
However, this didn't work - the returned height & width are both 0. The trouble may be that `canvasimg` hasn't yet been rendered (even after appending the entire app to `body`), so the height and width are 0.

I managed to get it working by re-rendering upon mousedown events. The full code:
```
var points = [ {top: '50%', left: '50%'}, {top: '25%', left: '75%'} ]
Imba.Events.register('mousedown')

tag #imgtag
    def onmousedown e
        @imgheight = $$(.canvasimg).dom():height
        @imgwidth = $$(.canvasimg).dom():width
        render

    def render
        <self>
            (var canvasimg = <img.canvasimg.size-to-window.max-height-70 src="img/interior-01.jpg">)
            (var markercontainer = <div.marker-container>
                for point in points
                    (var marker = <div.marker>
                        <img src="img/marker.png">
                    ).css(point)
            ).css({height: @imgheight, width: @imgwidth})

$$(body).append #imgtag
```

How would I use Imba to render this correctly from the start - page load - without any mousedown event? It doesn't work on Chrome though it worked on Firefox sometimes. Thanks for your advice.

**Comment by judofyr** [comment]
The issue here is that `render` is initially called before the DOM-node is inserted into the tree. You can usually solve these issues by have a separate `render` after you've inserted the tag in the correct place:

```imba
$$(body).append #imgtag
#imgtag.render  # re-render to set up height/widths
```

(This requires the latest version of Imba though)

**Comment by denyeo** [comment]
Thanks for the quick response. I did try #imgtag.render but it didn't work - it still produces a height and width of 0 - and I'm using the latest version 0.13.7. I can't figure out why it isn't actually re-rendering - maybe it's doing a diff and choosing not to re-render? For some reason, the mousedown event triggers the actual re-render. See http://udkk35438236.denyeo.koding.io/imba/

Any other ideas? Maybe you can point me to the relevant part of imba.js that determines whether to render or not. I tried looking but got a bit lost.

**Comment by judofyr** [comment]
Oh right, I'm guessing that the height/width is not available until the image is loaded. Try adding this in `render`:

```
console.log($$(.canvasimg).dom:complete)
```

And you'll see that the image isn't available at all when you call render. You probably want to re-render after the image has been loaded:

```
$$(.canvasimg).dom:onload = do |evt|
  #imgtag.render
```

**Comment by denyeo** [comment]
Works like a charm! I've now learned about the properties `tag.dom:complete` and `tag.dom:onload`, thanks to you. Much appreciated!

**Comment by denyeo** [comment]
Related issue: the following body.onresize property can't be set in Imba:
```
$$(body).dom:onresize = do
    #imgtag.render
    console.log "autoresizing"
```
Imba generates the correct code in app.js:
```
	q$$('body').dom().onresize = function() {
		id$('imgtag').render();
		return console.log("autoresizing");
	};
```
but it doesn't work in the browser - resizing doesn't cause any effect. Inspecting the `body` tag shows that .dom().onresize is undefined. Yet if I execute the above code directly in the console, the onresize function works. Any ideas?
