### ISSUE TITLE
body.onresize property seemingly can't be set

### ISSUE THREAD

**Issue by denyeo** [somebee/imba#30]
The following body.onresize property doesn't seem to be settable in Imba:
```
$$(body).dom:onresize = do
    #imgtag.render
    console.log "autoresizing"
```
Imba generates the correct code in app.js:
```
	q$$('body').dom().onresize = function() {
		id$('imgtag').render();
		return console.log("autoresizing");
	};
```
but it doesn't work in the browser - resizing doesn't cause any effect. Inspecting the `body` tag shows that .dom().onresize is undefined. Yet if I execute the above code directly in the console, the onresize function works. See http://udkk35438236.denyeo.koding.io/imba/

Any ideas? Could it because I need to register the 'resize' event in Imba?

Also, is there another way to detect and respond to window resizing?

**Comment by judofyr** [comment]
I guess you need to listen to events using `addEventListener`:

```imba
$$(body).dom.addEventListener("resize", &, false) do |evt|
  #imgtag.render
```

`addEventListerener` is the primary API for listening to events and is the "proper" way to do it. It has the advantage that you can have multiple listeners for the same event (as opposed to the `on`-properties).

**Comment by judofyr** [comment]
Oh, but actually, `onresize` is only available on `window`:

```
window.addEventListener("resize", &, false) do |evt|
  #imgtag.render

# or:
window.onresize = do |evt|
  #imgtag.render
```

**Comment by denyeo** [comment]
Great, it works. Initially I did try `window.onresize` but Imba compiled this to `window.setOnresize`. I then tried to find an alternative and found some W3Schools page saying that body.onresize was supported in all browsers, but you've shown me that it isn't.

I'm still a bit fuzzy on when to refer to tags directly (e.g. `#imgtag`) vs getting them from the DOM (e.g. `$$(.canvasimg)`).

A little correction - it needs to be `window:onresize`, else Imba will compile it to `window.setOnresize`.

**Comment by judofyr** [comment]
`#imgtag` will automatically create the tag if it doesn't exist yet, while `$$(#imgtag)` will just search for the tag in the current document. You usually use `$$` when you need to integrate with DOM nodes other places on the page. If the whole is built using Imba tags (with the `tag foo`-syntax) you very often don't need to use `$$` at all.

**Comment by judofyr** [comment]
A better homepage with more documentation is coming. Hopefully we'll have a blog too, and we might post some tutorials/guides as well.

**Comment by denyeo** [comment]
Okay, that explanation definitely helps, thanks.

I hope you do some good blogposts - that will get you attention and more users. I hope you cover stuff like the proper way to nest components.

**Comment by somebee** [comment]
@denyeo can you send me an email? (My email address is listed on http://github.com/somebee/). I'll try to help you more from there, and I can give you access to the new docs etc now (probably wont be openly deployed until next week).
