### ISSUE TITLE
imba watch (versions 0.13.8 and 0.13.9) are not compiling .imba files to .js files

### ISSUE THREAD

**Issue by mxvanzant** [somebee/imba#32]
Figured out code causing this:

	class Page
		prop name
		prop active

		def initialize name, active=false
			@name = name
			@active = active

		def get_current_user
			var url = "/current/user"
			var jqxhr = $.get(
				url,
				(do |data, status, xhr|
					console.log data
					console.log status
					@me.set_current_user data
				),
			 'json').fail(
					(do |xhr, status, error|
						@me().show_failure(xhr, status, error)
					)
				))

The extra ")" at the end caused the silent compiler error.

From output to console, it appears to work but no file is created and/or overwritten:

(compiling seems to be failing but without an error message -- I tried on a simple file and that compiled...)

	imba watch ./src
	dirname /home/mxvanzant/dev/tg/greenbook/code/gbwhat/public/app /home/mxvanzant/dev/tg/greenbook/code/gbwhat/public/app/src
	--- watch dir: /home/mxvanzant/dev/tg/greenbook/code/gbwhat/public/app/src
	--- write dir: /home/mxvanzant/dev/tg/greenbook/code/gbwhat/public/app/lib
	17:29:37 compile src/app.imba to lib/app.js - 

Also install gave this warning:

	npm update -g imba
	npm WARN optional dep failed, continuing fsevents@1.0.5
	/home/mxvanzant/bin/node/bin/imba -> /home/mxvanzant/bin/node/lib/node_modules/imba/bin/imba
	imba@0.13.9 /home/mxvanzant/bin/node/lib/node_modules/imba
	├── commander@2.9.0 (graceful-readlink@1.0.1)
	├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
	└── chokidar@1.2.0 (path-is-absolute@1.0.0, arrify@1.0.0, glob-parent@2.0.0, async-each@0.1.6, is-binary-path@1.0.1, is-glob@2.0.1, lodash.flatten@3.0.2, readdirp@2.0.0, anymatch@1.3.0)
	mxvanzant@tg-mv-toshiba ~/dev/tg/greenbook/code/gbwhat/public/app $ imba -v
	0.13.9

Directly running imba compile also does not work or give an error message...

Thanks!

**Comment by somebee** [comment]
I'll check it out and get back to you later tonight. Thanks for reporting

**Comment by mxvanzant** [comment]
Sindre,

Once I got rid of the extra ")" it compiled fine. But with the extra ")" 
it did not compile and there was no error message. So, no rush, it least 
it compiles. :)

Thanks!
Mike

**Comment by somebee** [comment]
Ok, great. It should definately have give you a warning, I'll try to fix it this weekend. By the way, I use tabs for indentation (not spaces), and there might be some bugs when you use spaces. We are considering moving over to 4 spaces as the default.

**Comment by somebee** [comment]
Should be fixed now. By the way, you can use & in method parameters to specify where the block should be.
```imba
setTimeout( (do alert('yes') ), 1000 )
# could be written like
setTimeout(&,1000) do alert('yes')

# same goes for your jqxhr
var jqxhr = $.get(url,&,'json') do |data,status,xhr|
	console.log data
	console.log status
	@me.set_current_user data

jqxhr.fail do |xhr, status, error|
	@me().show_failure(xhr, status, error)
```

Otherwise I'd recommend defining the callbacks first and passing them in. Nested chains like that become quite messy in Imba for the time being :)

**Comment by mxvanzant** [comment]
Thanks! I will try this.
