### ISSUE TITLE
`do` scope

### ISSUE THREAD

**Issue by sleewoo** [somebee/imba#33]
First of all thanks for new hope.

And i'd like to contribute my two cents regard  `do` generated functions scope...
I know there is `self`, but also there are scenarios when `self` does not help.

For example i'm requiring a set of functions from another file and injecting them into prototype:

```imba
module.exports =
  save: do |data|
    post data, do |response|
```

and compiled code looks like:

```javascript
(function(){
  var self = this;

  return module.exports = {
     save: function(data) {
```

so `save` function's `self` is Window,
though `this` is still correct cause it was inserted into base class's prototype,
so if `do` would behave like fat arrow this would make the deal...

There are of course "brute force" solutions like

```imba
var fn = do
  some code
post data, fn.bind(this)
```

or even

```imba
post data, _:bind({ |response|
  some code
}, this)
```

but as you can see they are just dirty hacks for such a elegant language.

So if `do` and `{ }` will behave like fat arrow we will have two ways to define functions:
- `def` will define regular functions bound to `self`
- `do` and `{}` will define scoped functions bound to `this`

makes sense?

thank you.

**Comment by sleewoo** [comment]
or at least allow this construction to work:

```imba
post data, {
  some code
}.bind(this)
```

actually it throws: `Module build failed: Parse error at [981:1]: Unexpected '.'`

**Comment by sleewoo** [comment]
err, i meant

```imba
post data, { |response|
  some code
}.bind(this)
```

**Comment by somebee** [comment]
We do consider adding a func-keyword (or similar) - that behaves exactly like do but without binding self (fat arrow). It's not totally clear to me what you are trying to achieve -- but you can use `this` in imba as well. `this` will always refer to the real `this`, just like in plain javascript. You can also define methods with `def` in imba. These are closed scopes (self is not brought in from outer scope). So if I understand you correctly, you might want to do:

```imba

export def save data
    post(data) do |response| console.log('something')
```

This compiles to:
```js
function save(data){
	return this.post(data,function() { return console.log('something'); });
}; exports.save = save;
```

**Comment by somebee** [comment]
I've promised to release the new site (with docs) this week, and we'll explain it there in more detail. But yes, lambda-style blocks are 'open', where their implicit self refers to the outer 'closed' scope. **You can still use `this` explicitly** though, it will never refer to anything else than the actual js `this`.

Method declarations (def) are 'closed' scopes, where the implicit self is not brought in from outer scopes.
And some more undocumented syntax I:
```
post data, { |response| some code }.bind(this)
```
is not valid in imba, we use regular parens instead:
```imba
post data, (|response| 
   some code
).bind(this)
```
This only works for methods with arguments though, so it is a rather clumsy syntax which might be deprecated in favour of the ruby-like syntax you wrote. To be on the safe side, you could just do this:
```imba
post data, (do
   some code
).bind(this)

# with parens
post data, (do |res|
   some code
).bind(this)
```

**Comment by sleewoo** [comment]
exactly, but inside `function() { return console.log('something'); }` the `this` will be Window,
that's the issue.

my idea was `do` to generate functions like this:

`function() { return console.log('something'); }.bind(this)`

**Comment by somebee** [comment]
No, not in this example.
```imba
export def save data
	post(data) do
		self # self here is the method on which save is called
```
The implicit self of a do block is always the closest 'closed' scope, not the outermost. def save has a closed scope, which the inner do will refer to.

**Comment by sleewoo** [comment]
ok, wonderful,
`export def` works perfect!
`self` is just what it is expected to be.
thank you.

Imba is impressive!
hoping it is here to stay.
keep doing marketing.
nowadays marketing is most important language feature :)
