### ISSUE TITLE
e.keychar is not working

### ISSUE THREAD

**Issue by madmaniak** [somebee/imba#41]
For input with defined <code>onkeypress e</code> when I use <code>e.keychar</code> I get:

> ReferenceError: TextEvent is not defined

```javascript
Imba.Event.prototype.keychar = function (){
  if (this.event() instanceof TextEvent) {
 // ...
```

**Comment by somebee** [comment]
Which browser?

**Comment by somebee** [comment]
I pushed a [fix](https://github.com/somebee/imba/commit/8d4aba0711aff9f7a82b28a3b5347fde92296a7f) for it now, but if you're using imba-rails it won't auto update. We'll push a new version of imba-rails tomorrow with the fix included. The `keychar` method itself should probably be deprecated, or at the very least renamed and improved. For now I think I'd fall back to e.which.

**Comment by madmaniak** [comment]
That's why I'm not using imba-rails. I'll check <code>e.which</code>. Thanks!

**Comment by madmaniak** [comment]
<code>e.which</code> for Escape is 0 on Firefox. Should be 27 according to <code>Imba.KEYMAP</code>. In debugger I see <code>keypress charCode=0, keyCode=27</code>

**Comment by somebee** [comment]
The whole Imba.KEYMAP thing ought to be rewritten or removed altogether. In the meantime you probably need to fall back to the native event using `e.event[:keyCode]` or `e.event[:charCode]` or something. This issue should probably be kept open until we've reworked that part of Imba.Event.
