### ISSUE TITLE
Support for instantiating tags with dynamic name/type

### ISSUE THREAD

**Issue by somebee** [somebee/imba#48]
@madmaniak proposed a syntax for creating tags by dynamic names. En example:

``` imba
var items = [{type: 'post', title: "Hello"},{type: 'article', title: "World"}]

var tags = for item in items
    <{item:type} object=item> # etc
```

This should be rather trivial, and I think the syntax is pretty consistent with the dynamic things in tag like `<div .{dynamic-class-name}>` and `<div@{custom-key}>`. What do you guys think?

**Comment by madmaniak** [comment]
Was it not trivial? :smile:
Still dreaming about
```js
<{item:type}[item]>
```
