### ISSUE TITLE
Remove chokidar dependency

### ISSUE THREAD

**Issue by somebee** [somebee/imba#49]
Chokidar is currently used by the CLI for watching files. We use it in a very basic manner, and it should be easy enough to roll our own. That will get rid of quite a few dependencies, including fsevents, which is the only binary / compiled dep right now. We do have a longterm goal of removing all dependencies, and chokidar is the most important to start with. The other two (chalk and commander) can be phased out later.

**Comment by judofyr** [comment]
We could also consider some support for Webpack/Browserify-config-generation in `imba`. `imba setup-webpack` could for instance add Webpack/Imba/Imba-loader to package.json and generate a `webpack.config.js` for you. And if `webpack.config.js` already exist it could print what changes you need to make.
