### ISSUE TITLE
Predeclare underscore (_) globally by default

### ISSUE THREAD

**Issue by somebee** [somebee/imba#52]
Lots of people are using lodash/underscore. By default, imba predeclares quite a few global variables (console, process, window, setTimeout, ...) I think we should also predeclare '_' the same way.

This way users won't struggle with this, and there will be no need for adding `extern _` to the top of every file that use it.

**Comment by judofyr** [comment]
I can see the advantage, although personally I would use lodash from NPM, so `var _ = require "lodash"` is good enough for me.

Are there any other externs we should have by default?

**Comment by somebee** [comment]
I use it like you, but this will still work even if we predeclare it :)
