### ISSUE TITLE
Render always touch the attribute with value = true

### ISSUE THREAD

**Issue by madmaniak** [somebee/imba#60]
Tested on ```<input required=variable_with_true>```.
http://imgur.com/cLZ7Jct
It'll work fine if we use <code>true</code> explicitly or convert the variable value to string.

**Comment by somebee** [comment]
So, it updates in the browser? Is this firefox again? I guess we need to make custom setters for required/readonly that checks the dom first for truthy value. I guess truth value should convert to required="required" and falsy value convert to removeAttribute('required') basically?

**Comment by madmaniak** [comment]
Oh sure it should be <code>required='required'</code>. I forgot about that and I was expecting boolean attributes in html which is wrong. So re-rendering issue has no matter in this case.

As you say true value should be converted to the name of the attribute (because we have more like this attributes e. g. *hidden*, *selected*).

It's firefox.

**Comment by somebee** [comment]
Yes, but if this:
```imba
tag item
    var dynamic = 'required'
    def render
        <self> <input required=dynamic>
```

Also 'touches' the dom in the sense that firefox tracks an update on every render, it is still something we'd need to fix.

**Comment by madmaniak** [comment]
Like I said it's fine if you use string.

**Comment by madmaniak** [comment]
I don't know how it works. But with *true* it might compare <code>true == "true"</code> at some point.

**Comment by somebee** [comment]
Sorry for the questions, is it fine if you use a dynamic string as well? I'm not sure whether we should treat these as attributes (dom.setAttribute) or properties (dom.required = ...). I'm testing in safari now, and treating it the same way we treat value (https://github.com/somebee/imba/blob/master/src/imba/dom.html.imba#L100-L105) seems correct.

**Comment by madmaniak** [comment]
Yes it is fine with dynamic string.

**Comment by somebee** [comment]
From 0.14.4 and onwards it should be `<item required=(truthy/falsy)>`. It will use the actual dom property instead of getAttribute/setAttribute. Same goes for disabled etc.
