### ISSUE TITLE
Default Tag Property Values

### ISSUE THREAD

**Issue by lukeed** [somebee/imba#75]
Feature Request:

Declaring default property values within tags.

Example:

```imba
tag example < div
	prop label = 'Title'
	prop value = null

	def render
		# nicer
		<self>
			@label
			<br>
			@value

		# instead of:
		<self>
			(@label or 'Title')
			<br>
			(@value or null)

```

Same syntax as method definitions' default param values

**Comment by lukeed** [comment]
It definitely wouldn't be a huge benefit; in fact, I'd be totally fine without it. 

I guess I'm just looking for feedback on the idea since I assumed that something like this was already an option.

**Comment by judofyr** [comment]
This already works today:

```
tag example
    prop label default: 'Title'
```

**Comment by lukeed** [comment]
Ah, great! Thanks!

**Comment by somebee** [comment]
This is already working as judofyr pointed out, but if you set default values other than strings and numbers (mutable objects) it is important to remember that all instances will refer to the same default value. It also doesn't work well with dom attributes right now.

**Comment by lukeed** [comment]
Thanks :+1: 
The way I handle it is if a default is something more complicated than a string or an empty-anything, it should be declared within the method. For readability, if nothing else
