### ISSUE TITLE
Duplicative `subclass` func

### ISSUE THREAD

**Issue by lukeed** [somebee/imba#78]
For every `extend` used, an additional `subclass` function is created inside the compiled output.

```js
// helper for subclassing
function subclass$(obj,sup) {
	for (var k in sup) {
		if (sup.hasOwnProperty(k)) obj[k] = sup[k];
	};
	// obj.__super__ = sup;
	obj.prototype = Object.create(sup.prototype);
	obj.__super__ = obj.prototype.__super__ = sup.prototype;
	obj.prototype.initialize = obj.prototype.constructor = obj;
};
```

So, 30 extensions = 30 x `subclass`.

All these suclass helpers should be removed in favor of [`Imba.subclass`](https://github.com/somebee/imba/blob/master/src/imba/imba.imba#L39), since they're the same.

**Comment by lukeed** [comment]
Great example of what I mentioned in #53 

If `--lib` flag: use `Imba.subclass`.
Else: stub out internal `subclass$` helper

**Comment by somebee** [comment]
Ouch, this is clearly a bug. It doesn't happen here though..
```imba
class A
class B < A
class C < A
```
```js
function subclass$(obj,sup) {
	for (var k in sup) {
		if (sup.hasOwnProperty(k)) obj[k] = sup[k];
	};
	// obj.__super__ = sup;
	obj.prototype = Object.create(sup.prototype);
	obj.__super__ = obj.prototype.__super__ = sup.prototype;
	obj.prototype.initialize = obj.prototype.constructor = obj;
};

function A(){ };


function B(){ return A.apply(this,arguments) };

subclass$(B,A);

function C(){ return A.apply(this,arguments) };

subclass$(C,A);
```
Also, there is a  --standalone flag for the CLI that is currently [disabled](https://github.com/somebee/imba/blob/master/src/compiler/cli.imba#L300-L301) that will do what you suggest :) Right now Imba will always generate helpers when / if needed in each file (but it should never add multiple copies of each helper). If you pass hasRuntime: yes to the compiler it does instead use Imba.subclass, Imba.iterable etc, but it is not possible to do via the CLI atm.

**Comment by lukeed** [comment]
Right, sorry. I meant to specify that it redeclares the `subclass$` helper in every file, which is the traditional way to handle each class.

Maybe it's worth reenabling that flag? 

On a selfish level, it strips 210 lines of code for me (30 classes x 7 lines).
On a larger level, I think the "split" between the language and the library will be great for Imba.
