### ISSUE TITLE
20 or 10 times faster than React? 

### ISSUE THREAD

**Issue by brunocascio** [somebee/imba#84]
Web imba.io:

![imba.io Docs](https://cloud.githubusercontent.com/assets/2397875/16873531/5cf1651e-4a6a-11e6-82ef-310b5cf9fd68.png)

----

Github Readme:

![Github Readme](https://cloud.githubusercontent.com/assets/2397875/16873532/5cf1d904-4a6a-11e6-8fa0-1a78abcc85e2.png)

:)

**Comment by somebee** [comment]
It varies from browser to browser, and we haven't benchmarked against the latest version of React yet, but our current 0.15 alpha is at least 50x faster on safari :) You can run the benchmark [here](http://somebee.github.io/todomvc-render-benchmark/index.html).

For many other benchmarks you will probably **only** see an improvement of 2-5x over React, but this is for microbenchmarks where most of the time is spent in browser code (not inside the frameworks). We firmly believe that this type of benchmark is much more relevant for real world performance. For some additional discussion regarding the benchmark, see [here](https://discuss.reactjs.org/t/comparing-dom-diffing-with-imba-which-claims-to-be-35x-faster-than-react/1824/7?u=somebee) and [here](https://github.com/somebee/imba/issues/9).

We will update the readme and site as soon as we release 0.15.0 as the stable version (it can now be installed through `npm install imba@dev`.

**Comment by brunocascio** [comment]
Actually React's version is `15.2.1`. Could you add this?

[React](https://facebook.github.io/react/index.html)

I'll try imba soon. I love your syntax.

Thanks!
