### ISSUE TITLE
Dynamic cache-key with side effects does not work

### ISSUE THREAD

**Issue by somebee** [somebee/imba#89]
`<div@{i++}>` ends up incrementing the counter twice.

**Comment by madmaniak** [comment]
What's the use case for dynamic cache-key?

**Comment by somebee** [comment]
It is useful when you want to render tags that should be cached but are not inside <self> or named tags. Here is a very short (and clumsy) explanation at [scrimba.com - What is the use-case for dynamic cache-keys?](https://scrimba.com/somebee/53) :)

**Comment by madmaniak** [comment]
Oh sorry, this part I know - I was just wondering what's this construct for <code>{i++}</code>?
But despite that, this looks awesome :scream_cat: I've learnt I don't need __render__ and __self__ at the and of <code>build</code> anymore. Probably looking for {object:id} by default if exist would be too much and hit performance. What do you think?
